import Head from 'next/head';
import Footer from './Footer';
import Navbar from './Navbar';
import { useEffect } from 'react'
import { useDispatch } from "react-redux";
import { fetchAuthMe } from "../redux/slice/auth";

const Layout = ({ children }) => {
  const dispatch = useDispatch()
  // Нуждается в доработке
  useEffect(() => {
    dispatch(fetchAuthMe())
  }, [])
  return (
    <>
      <Head>
        <title>Eddy Cuts</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <link rel="icon" href="/svg/logo.svg" />
      </Head>
      <Navbar />
      {children}
      <Footer />
    </>
  );
};

export default Layout;
